default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USER") %>
  password: <%= ENV.fetch("RAILS_DB_PASS") %>

development:
  <<: *default
  database: scorer_dev

test:
  <<: *default
  database: scorer_test

production:
  <<: *default
  database: scorer_prod
